@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Otavio Pinto",
    "email": "otaviopinto2@email.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "paulotouret@email.com",
    "password": "123456"
}

###

# @name create_questions
POST {{baseUrl}}/questions
Content-Type: application/json
# Authorization: Bearer {{authToken}}

{
    "title": "New question 012",
    "content": "Content of question"
}


###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}
